name: unipal_app
description: UniPal mobile app made with Flutter SDK

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  animated_custom_dropdown: ^1.2.0
  cached_network_image: ^3.2.0
  clock: ^1.1.0
  cupertino_icons: ^1.0.4
  dio: ^4.0.6
  dio_http2_adapter: ^2.0.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.3
  flutter_secure_storage: ^5.0.2
  flutter_spinkit: ^5.1.0
  freezed_annotation: ^2.0.3
  golden_toolkit: ^0.13.0
  google_fonts: ^2.3.2
  hooks_riverpod: 2.0.0-dev.6
  intl: ^0.17.0
  json_annotation: ^4.5.0
  mobile_scanner: ^1.0.0
  mockito: ^5.1.0
  sentry_flutter: ^6.4.0
  shared_preferences: ^2.0.13
  table_sticky_headers: ^2.0.0
  time: ^2.1.0

dev_dependencies:
  build_runner: ^2.1.10
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3
  json_serializable: ^6.2.0
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
